# Site settings
main_color: "red"
# blue red pink yellow
title: "Daily Astrology & Palm Reading"
app_name: "Daily Astrology & Palm Reading"
app_domain: "astrohoroscope.me"
support_email_address: "support@astrohoroscope.me"
appstore_url: "https://itunes.apple.com/us/app/id1434368697"
#url: "http://localhost:4000/"
url: "https://astrohoroscope.co/"
# Build settings
markdown: kramdown
